version: '3'
services:
  db:
    image: postgres
    env_file:
      - ./usof/.env
    ports:
      - "8000:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
  web:
    restart: always
    build: .
    volumes:
      - .:/usof
    depends_on:
      - db
    ports:
      - "5050:8000"