# Generated by Django 4.2.6 on 2023-11-01 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usof_api_post', '0002_initial'),
        ('usof_api_comments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='post_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='usof_api_post.post'),
            preserve_default=False,
        ),
    ]
