# Generated by Django 4.2.6 on 2023-11-04 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usof_api_comments', '0002_comment_post_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='comment',
            name='publish_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
