# Generated by Django 4.2.6 on 2023-11-05 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usof_api_post', '0002_initial'),
        ('usof_api_comments', '0003_alter_comment_author_alter_comment_publish_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='post_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='usof_api_post.post'),
        ),
    ]
