# Generated by Django 4.2.6 on 2023-11-05 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usof_api_comments', '0004_alter_comment_post_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='post_id',
            field=models.IntegerField(),
        ),
    ]
