# Generated by Django 4.2.6 on 2023-10-13 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usof_api', '0003_user_is_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_staff',
        ),
    ]
