# Generated by Django 4.2.6 on 2023-10-14 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usof_api', '0004_remove_user_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
