# Generated by Django 4.2.6 on 2023-11-06 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=100)),
                ('publish_date', models.DateField(auto_now_add=True, null=True)),
                ('post_id', models.IntegerField()),
                ('comment_id', models.IntegerField()),
                ('type', models.BooleanField()),
            ],
        ),
    ]
