# Generated by Django 4.2.6 on 2023-11-06 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usof_api_like', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='author',
            new_name='author_of_like',
        ),
    ]
