# Generated by Django 4.2.6 on 2023-11-06 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usof_api_like', '0002_rename_author_like_author_of_like'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='author_of_like',
            new_name='author',
        ),
    ]
