# Generated by Django 4.2.6 on 2023-10-21 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usof_api_user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(db_column='is_active', default=False),
        ),
    ]
