# Generated by Django 4.2.6 on 2023-10-26 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usof_api_user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
