# Generated by Django 4.2.6 on 2023-10-21 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usof_api_user', '0002_alter_user_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_active',
        ),
    ]
