# Generated by Django 4.2.6 on 2023-10-31 12:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usof_api_post', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('usof_api_categories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='categories',
            field=models.ManyToManyField(blank=True, null=True, to='usof_api_categories.category'),
        ),
    ]
