# Generated by Django 4.2.6 on 2023-10-30 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usof_api_post', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='author_id',
            new_name='author',
        ),
    ]
